# Generated by Django 3.0.6 on 2020-06-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScriptFile',
        ),
    ]
